table Users
    lineageTag: 6e92016b-d0e0-5f66-99d3-c2569ca195b2

    column RunDate
        dataType: dateTime
        formatString: Short Date
        lineageTag: b2b569c0-7d97-50d4-9ea0-01b0210aba25
        summarizeBy: none
        sourceColumn: RunDate

    column Id
        dataType: string
        lineageTag: 980ca83d-b68d-5e73-95c4-538d448c1cd9
        summarizeBy: none
        sourceColumn: Id

    column DisplayName
        dataType: string
        lineageTag: 47e25139-1c58-56ad-a8ed-c3e37ab22508
        summarizeBy: none
        sourceColumn: DisplayName

    column UserPrincipalName
        dataType: string
        lineageTag: 0234716c-cecc-5ddb-80f8-6271bb8841da
        summarizeBy: none
        sourceColumn: UserPrincipalName

    column Mail
        dataType: string
        lineageTag: 2a5f76f2-8460-5db9-a2cf-c698d00c29f2
        summarizeBy: none
        sourceColumn: Mail

    column UserType
        dataType: string
        lineageTag: cac1e6bd-9d80-5a4e-933d-6ca650163213
        summarizeBy: none
        sourceColumn: UserType

    column AccountEnabled
        dataType: boolean
        lineageTag: 976c33a1-bf0c-5d3f-ab51-3541bf6d727a
        summarizeBy: none
        sourceColumn: AccountEnabled

    column CreatedDateTime
        dataType: dateTime
        formatString: General Date
        lineageTag: 8b6ee007-aec0-5378-a249-2debf18b5e25
        summarizeBy: none
        sourceColumn: CreatedDateTime

    column Department
        dataType: string
        lineageTag: 54c516cf-5707-5fda-a53c-1035cf4db997
        summarizeBy: none
        sourceColumn: Department

    column JobTitle
        dataType: string
        lineageTag: 7762811d-cd64-5b4a-a412-d0183668236e
        summarizeBy: none
        sourceColumn: JobTitle

    column City
        dataType: string
        lineageTag: d9400fe8-3146-599f-8d86-53d55d35d0e1
        summarizeBy: none
        sourceColumn: City

    column Country
        dataType: string
        lineageTag: 419bde6a-e999-565e-989d-0059ac3b26a7
        summarizeBy: none
        sourceColumn: Country

    column ManagerId
        dataType: string
        lineageTag: efaa5b55-5027-553f-b971-e5e11208366e
        summarizeBy: none
        sourceColumn: ManagerId

    column ManagerUserPrincipalName
        dataType: string
        lineageTag: 42f5d786-b586-55c9-b840-3d0aa0595a69
        summarizeBy: none
        sourceColumn: ManagerUserPrincipalName

    partition Users = m
        mode: import
        source =
            let
                Source = Csv.Document(File.Contents(CsvFolder & "\users.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                AllText = Table.TransformColumnTypes(Promoted, List.Transform(Table.ColumnNames(Promoted), each {_, type text})),
                Cleaned = Table.ReplaceValue(AllText, "", null, Replacer.ReplaceValue, Table.ColumnNames(AllText)),
                ParseUtc = (value as nullable text) as nullable datetime =>
                    if value = null then null else DateTime.FromText(value, [Format="yyyy-MM-dd'T'HH:mm:ss'Z'", Culture="en-US"]),
                Parsed = Table.TransformColumns(Cleaned, {{"CreatedDateTime", ParseUtc, type datetime}}),
                #"Changed Type" = Table.TransformColumnTypes(Parsed, {{"RunDate", type date}, {"AccountEnabled", type logical}})
            in
                #"Changed Type"

    annotation PBI_ResultType = Table
