/// One row per Activity Explorer event (Get-ActivityExplorerEvents.ps1 /
/// activity-explorer-events.csv): label applied/changed/removed, protection
/// changes, DLP matches/enforcements/overrides with justification,
/// retention label changes, and Copilot/AI interactions. Drives Label
/// activity, DLP and Retention page measures.
table ActivityExplorerEvents

	column RecordIdentity
		dataType: string
		sourceColumn: RecordIdentity
		summarizeBy: none

	column Happened
		dataType: dateTime
		formatString: General Date
		sourceColumn: Happened
		summarizeBy: none

	column EventDate
		dataType: dateTime
		formatString: Long Date
		sourceColumn: EventDate
		summarizeBy: none

	column Activity
		dataType: string
		sourceColumn: Activity
		summarizeBy: none

	column ActivityRaw
		dataType: string
		sourceColumn: ActivityRaw
		summarizeBy: none

	column ActivityCategory
		dataType: string
		sourceColumn: ActivityCategory
		summarizeBy: none

	column Workload
		dataType: string
		sourceColumn: Workload
		summarizeBy: none

	column Application
		dataType: string
		sourceColumn: Application
		summarizeBy: none

	column User
		dataType: string
		sourceColumn: User
		summarizeBy: none

	column UserType
		dataType: string
		sourceColumn: UserType
		summarizeBy: none

	column ItemName
		dataType: string
		sourceColumn: ItemName
		summarizeBy: none

	column FilePath
		dataType: string
		sourceColumn: FilePath
		summarizeBy: none

	column FullUrl
		dataType: string
		sourceColumn: FullUrl
		summarizeBy: none

	column FileExtension
		dataType: string
		sourceColumn: FileExtension
		summarizeBy: none

	column DeviceName
		dataType: string
		sourceColumn: DeviceName
		summarizeBy: none

	column Platform
		dataType: string
		sourceColumn: Platform
		summarizeBy: none

	column SensitivityLabel
		dataType: string
		sourceColumn: SensitivityLabel
		summarizeBy: none

	column OldSensitivityLabel
		dataType: string
		sourceColumn: OldSensitivityLabel
		summarizeBy: none

	column SensitivityLabelPolicyId
		dataType: string
		sourceColumn: SensitivityLabelPolicyId
		summarizeBy: none

	column LabelEventType
		dataType: string
		sourceColumn: LabelEventType
		summarizeBy: none

	column IsLabelDowngrade
		dataType: string
		sourceColumn: IsLabelDowngrade
		summarizeBy: none

	column HowApplied
		dataType: string
		sourceColumn: HowApplied
		summarizeBy: none

	column Justification
		dataType: string
		sourceColumn: Justification
		summarizeBy: none

	column IsProtected
		dataType: string
		sourceColumn: IsProtected
		summarizeBy: none

	column IsProtectedBefore
		dataType: string
		sourceColumn: IsProtectedBefore
		summarizeBy: none

	column ProtectionEventType
		dataType: string
		sourceColumn: ProtectionEventType
		summarizeBy: none

	column ProtectionType
		dataType: string
		sourceColumn: ProtectionType
		summarizeBy: none

	column ProtectionOwner
		dataType: string
		sourceColumn: ProtectionOwner
		summarizeBy: none

	column RMSEncrypted
		dataType: string
		sourceColumn: RMSEncrypted
		summarizeBy: none

	column RetentionLabel
		dataType: string
		sourceColumn: RetentionLabel
		summarizeBy: none

	column OldRetentionLabel
		dataType: string
		sourceColumn: OldRetentionLabel
		summarizeBy: none

	/// The collector stores the compliance-tag name, not the tag GUID.
	/// Removals leave RetentionLabel blank and keep the previous name in
	/// OldRetentionLabel, so the relationship key falls back to that.
	column 'Retention Label Key' =
			IF(
			    ActivityExplorerEvents[RetentionLabel] <> "",
			    ActivityExplorerEvents[RetentionLabel],
			    ActivityExplorerEvents[OldRetentionLabel]
			)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column SensitiveInfoTypeName
		dataType: string
		sourceColumn: SensitiveInfoTypeName
		summarizeBy: none

	column SensitiveInfoTypeCount
		dataType: int64
		sourceColumn: SensitiveInfoTypeCount
		summarizeBy: sum

	column SensitiveInfoTypeConfidence
		dataType: int64
		sourceColumn: SensitiveInfoTypeConfidence
		summarizeBy: none

	column PolicyId
		dataType: string
		sourceColumn: PolicyId
		summarizeBy: none

	column PolicyName
		dataType: string
		sourceColumn: PolicyName
		summarizeBy: none

	column PolicyMode
		dataType: string
		sourceColumn: PolicyMode
		summarizeBy: none

	column RuleId
		dataType: string
		sourceColumn: RuleId
		summarizeBy: none

	column RuleName
		dataType: string
		sourceColumn: RuleName
		summarizeBy: none

	column RuleActions
		dataType: string
		sourceColumn: RuleActions
		summarizeBy: none

	column EnforcementMode
		dataType: string
		sourceColumn: EnforcementMode
		summarizeBy: none

	column FalsePositive
		dataType: string
		sourceColumn: FalsePositive
		summarizeBy: none

	column DlpPolicyMatchId
		dataType: string
		sourceColumn: DlpPolicyMatchId
		summarizeBy: none

	partition ActivityExplorerEvents = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CsvFolder & "\activity-explorer-events.csv"), [Delimiter=",", Columns=43, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {
				        {"RecordIdentity", type text},
				        {"Activity", type text}, {"ActivityRaw", type text}, {"ActivityCategory", type text},
				        {"Workload", type text}, {"Application", type text}, {"User", type text}, {"UserType", type text},
				        {"ItemName", type text}, {"FilePath", type text}, {"FullUrl", type text}, {"FileExtension", type text},
				        {"DeviceName", type text}, {"Platform", type text}, {"SensitivityLabel", type text},
				        {"OldSensitivityLabel", type text}, {"SensitivityLabelPolicyId", type text}, {"LabelEventType", type text},
				        {"IsLabelDowngrade", type text}, {"HowApplied", type text}, {"Justification", type text},
				        {"IsProtected", type text}, {"IsProtectedBefore", type text}, {"ProtectionEventType", type text},
				        {"ProtectionType", type text}, {"ProtectionOwner", type text}, {"RMSEncrypted", type text},
				        {"RetentionLabel", type text}, {"OldRetentionLabel", type text}, {"SensitiveInfoTypeName", type text},
				        {"PolicyId", type text}, {"PolicyName", type text}, {"PolicyMode", type text}, {"RuleId", type text}, {"RuleName", type text},
				        {"RuleActions", type text}, {"EnforcementMode", type text}, {"FalsePositive", type text},
				        {"DlpPolicyMatchId", type text}
				    }),
				    ParsedDates = Table.TransformColumns(ChangedType, {
				        {"EventDate", each ParseOptionalDate(_), type date}
				    }),
				    ParsedUtc = Table.TransformColumns(ParsedDates, {
				        {"Happened", each ParseUtcDateTime(_), type datetime}
				    }),
				    ParsedCounts = Table.TransformColumns(ParsedUtc, {
				        {"SensitiveInfoTypeCount", each ParseOptionalInt64(_), Int64.Type},
				        {"SensitiveInfoTypeConfidence", each ParseOptionalInt64(_), Int64.Type}
				    })
				in
				    ParsedCounts
