/// One row per resource Copilot accessed, flattened out of
/// CopilotEventData.AccessedResources on each CopilotInteraction audit
/// record (Get-CopilotAccessedResources.ps1 / copilot-accessed-resources.csv).
/// Drives the Copilot and AI page: labeled content Copilot read, resources
/// blocked by policy, and DLP-for-Copilot matches.
table CopilotAccessedResources

	column RecordId
		dataType: string
		sourceColumn: RecordId
		summarizeBy: none

	column CreationTime
		dataType: dateTime
		formatString: General Date
		sourceColumn: CreationTime
		summarizeBy: none

	column EventDate
		dataType: dateTime
		formatString: Long Date
		sourceColumn: EventDate
		summarizeBy: none

	column Operation
		dataType: string
		sourceColumn: Operation
		summarizeBy: none

	column RecordType
		dataType: string
		sourceColumn: RecordType
		summarizeBy: none

	column Workload
		dataType: string
		sourceColumn: Workload
		summarizeBy: none

	column UserId
		dataType: string
		sourceColumn: UserId
		summarizeBy: none

	column UserKey
		dataType: string
		sourceColumn: UserKey
		summarizeBy: none

	column UserType
		dataType: string
		sourceColumn: UserType
		summarizeBy: none

	column AppHost
		dataType: string
		sourceColumn: AppHost
		summarizeBy: none

	column AppIdentity
		dataType: string
		sourceColumn: AppIdentity
		summarizeBy: none

	column AgentId
		dataType: string
		sourceColumn: AgentId
		summarizeBy: none

	column AgentName
		dataType: string
		sourceColumn: AgentName
		summarizeBy: none

	column ThreadId
		dataType: string
		sourceColumn: ThreadId
		summarizeBy: none

	column ResourceId
		dataType: string
		sourceColumn: ResourceId
		summarizeBy: none

	column ResourceName
		dataType: string
		sourceColumn: ResourceName
		summarizeBy: none

	column ResourceType
		dataType: string
		sourceColumn: ResourceType
		summarizeBy: none

	column ResourceAction
		dataType: string
		sourceColumn: ResourceAction
		summarizeBy: none

	column SiteUrl
		dataType: string
		sourceColumn: SiteUrl
		summarizeBy: none

	column ListItemUniqueId
		dataType: string
		sourceColumn: ListItemUniqueId
		summarizeBy: none

	column SensitivityLabelId
		dataType: string
		sourceColumn: SensitivityLabelId
		summarizeBy: none

	column Status
		dataType: string
		sourceColumn: Status
		summarizeBy: none

	column AccessBlocked
		dataType: string
		sourceColumn: AccessBlocked
		summarizeBy: none

	column XpiaDetected
		dataType: string
		sourceColumn: XpiaDetected
		summarizeBy: none

	column PolicyId
		dataType: string
		sourceColumn: PolicyId
		summarizeBy: none

	column PolicyName
		dataType: string
		sourceColumn: PolicyName
		summarizeBy: none

	column PolicyRules
		dataType: string
		sourceColumn: PolicyRules
		summarizeBy: none

	partition CopilotAccessedResources = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CsvFolder & "\copilot-accessed-resources.csv"), [Delimiter=",", Columns=27, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {
				        {"RecordId", type text}, {"Operation", type text},
				        {"RecordType", type text}, {"Workload", type text}, {"UserId", type text}, {"UserKey", type text},
				        {"UserType", type text}, {"AppHost", type text}, {"AppIdentity", type text}, {"AgentId", type text},
				        {"AgentName", type text}, {"ThreadId", type text}, {"ResourceId", type text}, {"ResourceName", type text},
				        {"ResourceType", type text}, {"ResourceAction", type text}, {"SiteUrl", type text}, {"ListItemUniqueId", type text},
				        {"SensitivityLabelId", type text}, {"Status", type text}, {"AccessBlocked", type text}, {"XpiaDetected", type text},
				        {"PolicyId", type text}, {"PolicyName", type text}, {"PolicyRules", type text}
				    }),
				    ParsedDates = Table.TransformColumns(ChangedType, {
				        {"EventDate", each ParseOptionalDate(_), type date}
				    }),
				    ParsedUtc = Table.TransformColumns(ParsedDates, {
				        {"CreationTime", each ParseUtcDateTime(_), type datetime}
				    })
				in
				    ParsedUtc
