/// The tenant's user directory (shared Entra users collector / users.csv). One row per
/// user, plus the manager-chain hierarchy built from ManagerId with PATH()
/// and the anonymize-toggle pseudonym used by the report's anonymize slicer.
table Users

	column RunDate
		dataType: dateTime
		formatString: Long Date
		sourceColumn: RunDate
		summarizeBy: none

	column UserId
		dataType: string
		sourceColumn: Id
		summarizeBy: none

	column DisplayName
		dataType: string
		sourceColumn: DisplayName
		summarizeBy: none

	column UserPrincipalName
		dataType: string
		sourceColumn: UserPrincipalName
		summarizeBy: none

	column Mail
		dataType: string
		sourceColumn: Mail
		summarizeBy: none

	column UserType
		dataType: string
		sourceColumn: UserType
		summarizeBy: none

	column AccountEnabled
		dataType: string
		sourceColumn: AccountEnabled
		summarizeBy: none

	column CreatedDateTime
		dataType: dateTime
		formatString: General Date
		sourceColumn: CreatedDateTime
		summarizeBy: none

	column Department
		dataType: string
		sourceColumn: Department
		summarizeBy: none

	column JobTitle
		dataType: string
		sourceColumn: JobTitle
		summarizeBy: none

	column City
		dataType: string
		sourceColumn: City
		summarizeBy: none

	column Country
		dataType: string
		sourceColumn: Country
		summarizeBy: none

	column ManagerId
		dataType: string
		sourceColumn: ManagerId
		summarizeBy: none

	column ManagerUserPrincipalName
		dataType: string
		sourceColumn: ManagerUserPrincipalName
		summarizeBy: none

	/// Parent-child hierarchy DAX pattern (PATH over UserId/ManagerId) for
	/// the Org decomposition page's manager-chain drill-down.
	column 'Manager Path' = PATH(Users[UserId], Users[ManagerId])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Manager Path Length' = PATHLENGTH(Users[Manager Path])
		dataType: int64
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 1 Id' = PATHITEM(Users[Manager Path], 1)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 2 Id' = PATHITEM(Users[Manager Path], 2)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 3 Id' = PATHITEM(Users[Manager Path], 3)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 4 Id' = PATHITEM(Users[Manager Path], 4)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 5 Id' = PATHITEM(Users[Manager Path], 5)
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 1 Name' = LOOKUPVALUE(Users[DisplayName], Users[UserId], Users[Level 1 Id])
		dataType: string
		type: calculated
		summarizeBy: none

	column 'Level 2 Name' = LOOKUPVALUE(Users[DisplayName], Users[UserId], Users[Level 2 Id])
		dataType: string
		type: calculated
		summarizeBy: none

	column 'Level 3 Name' = LOOKUPVALUE(Users[DisplayName], Users[UserId], Users[Level 3 Id])
		dataType: string
		type: calculated
		summarizeBy: none

	column 'Level 4 Name' = LOOKUPVALUE(Users[DisplayName], Users[UserId], Users[Level 4 Id])
		dataType: string
		type: calculated
		summarizeBy: none

	column 'Level 5 Name' = LOOKUPVALUE(Users[DisplayName], Users[UserId], Users[Level 5 Id])
		dataType: string
		type: calculated
		summarizeBy: none

	/// Stable per-user pseudonym: a dense rank over UserId, so the same user
	/// always gets the same "User 00001"-style label while the data is
	/// unchanged. Used by the [Display Name] measure when the report-wide
	/// anonymize toggle is on.
	/// ALL(Users[UserId]) — not ALL(Users). Ranking over the whole table makes
	/// this column depend on every other calculated column, which is a
	/// circular dependency once those columns also exist.
	column 'Anonymous Id' = RANKX(ALL(Users[UserId]), Users[UserId], , ASC, Dense)
		dataType: int64
		type: calculated
		isHidden
		summarizeBy: none

	column 'Anonymous Display Name' = "User " & FORMAT(Users[Anonymous Id], "00000")
		dataType: string
		type: calculated
		summarizeBy: none

	column 'Level 1 Anonymous Name' = LOOKUPVALUE(Users[Anonymous Display Name], Users[UserId], Users[Level 1 Id])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 2 Anonymous Name' = LOOKUPVALUE(Users[Anonymous Display Name], Users[UserId], Users[Level 2 Id])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 3 Anonymous Name' = LOOKUPVALUE(Users[Anonymous Display Name], Users[UserId], Users[Level 3 Id])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 4 Anonymous Name' = LOOKUPVALUE(Users[Anonymous Display Name], Users[UserId], Users[Level 4 Id])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	column 'Level 5 Anonymous Name' = LOOKUPVALUE(Users[Anonymous Display Name], Users[UserId], Users[Level 5 Id])
		dataType: string
		type: calculated
		isHidden
		summarizeBy: none

	hierarchy 'Manager Chain'
		level 'Level 1'
			column: 'Level 1 Name'
		level 'Level 2'
			column: 'Level 2 Name'
		level 'Level 3'
			column: 'Level 3 Name'
		level 'Level 4'
			column: 'Level 4 Name'
		level 'Level 5'
			column: 'Level 5 Name'

	partition Users = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CsvFolder & "\users.csv"), [Delimiter=",", Columns=14, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    PromotedHeaders = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    ChangedType = Table.TransformColumnTypes(PromotedHeaders, {
				        {"Id", type text}, {"DisplayName", type text}, {"UserPrincipalName", type text},
				        {"Mail", type text}, {"UserType", type text}, {"AccountEnabled", type text},
				        {"Department", type text}, {"JobTitle", type text}, {"City", type text}, {"Country", type text},
				        {"ManagerId", type text}, {"ManagerUserPrincipalName", type text}
				    }),
				    ParsedRun = Table.TransformColumns(ChangedType, {
				        {"RunDate", each ParseOptionalDate(_), type date}
				    }),
				    ParsedUtc = Table.TransformColumns(ParsedRun, {
				        {"CreatedDateTime", each ParseUtcDateTime(_), type datetime}
				    })
				in
				    ParsedUtc
