table Users
    lineageTag: b7981f86-b133-5f82-bf27-d8f2154fefd6

    column RunDate
        dataType: dateTime
        formatString: Short Date
        lineageTag: 46ecea67-0245-5b6b-aa2c-c7122bac4997
        summarizeBy: none
        sourceColumn: RunDate

    column Id
        dataType: string
        lineageTag: db44fe51-ce4d-5ff7-bcdd-edfde1f3b918
        summarizeBy: none
        sourceColumn: Id

    column DisplayName
        dataType: string
        lineageTag: c95b2681-5b8e-5aa2-bb5a-964b5ae03020
        summarizeBy: none
        sourceColumn: DisplayName

    column UserPrincipalName
        dataType: string
        lineageTag: 9b3f7255-a96d-5e8e-a3c9-f604feac10db
        summarizeBy: none
        sourceColumn: UserPrincipalName

    column Mail
        dataType: string
        lineageTag: e7797655-839c-53be-bff5-e5e932de5e46
        summarizeBy: none
        sourceColumn: Mail

    column UserType
        dataType: string
        lineageTag: 81605b21-1fb5-5ed2-b515-f98cdd3122e4
        summarizeBy: none
        sourceColumn: UserType

    column AccountEnabled
        dataType: boolean
        lineageTag: 5f2bcbcd-b9a7-53a4-9bfe-75b830a8fcde
        summarizeBy: none
        sourceColumn: AccountEnabled

    column CreatedDateTime
        dataType: dateTime
        formatString: General Date
        lineageTag: 4bcb7eca-320e-541e-b70a-48bc5d9e732f
        summarizeBy: none
        sourceColumn: CreatedDateTime

    column Department
        dataType: string
        lineageTag: a0d32cac-0bce-5080-8a05-f30c26deb6ff
        summarizeBy: none
        sourceColumn: Department

    column JobTitle
        dataType: string
        lineageTag: 7d006840-89b9-5179-b5b9-e52074e0ba3c
        summarizeBy: none
        sourceColumn: JobTitle

    column City
        dataType: string
        lineageTag: f1cefb48-82ce-5ff2-8fa6-b197b822032d
        summarizeBy: none
        sourceColumn: City

    column Country
        dataType: string
        lineageTag: da077854-a091-53e2-9233-7a5093cd3ff5
        summarizeBy: none
        sourceColumn: Country

    column ManagerId
        dataType: string
        lineageTag: f911dbcc-f1cc-5c7c-96ba-8a5557f20455
        summarizeBy: none
        sourceColumn: ManagerId

    column ManagerUserPrincipalName
        dataType: string
        lineageTag: d555d45b-fff7-5102-bf48-03efd0d4d705
        summarizeBy: none
        sourceColumn: ManagerUserPrincipalName

    partition Users = m
        mode: import
        source =
            let
                Source = Csv.Document(File.Contents(CsvFolder & "\users.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
                Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
                AllText = Table.TransformColumnTypes(Promoted, List.Transform(Table.ColumnNames(Promoted), each {_, type text})),
                Cleaned = Table.ReplaceValue(AllText, "", null, Replacer.ReplaceValue, Table.ColumnNames(AllText)),
                // Collector stamps are UTC "yyyy-MM-ddTHH:mm:ssZ". DateTime.FromText only
                // accepts the Z designator when the format treats it as a literal, and that
                // keeps the UTC clock time instead of shifting it to the model time zone.
                ParseUtc = (value as nullable text) as nullable datetime =>
                    if value = null then null else DateTime.FromText(value, [Format="yyyy-MM-dd'T'HH:mm:ss'Z'", Culture="en-US"]),
                Parsed = Table.TransformColumns(Cleaned, {{"CreatedDateTime", ParseUtc, type datetime}}),
                #"Changed Type" = Table.TransformColumnTypes(Parsed, {{"RunDate", type date}, {"AccountEnabled", type logical}})
            in
                #"Changed Type"

    annotation PBI_ResultType = Table
